### ISSUE TITLE
Decks to consider

### ISSUE THREAD

**Issue by mstenemo** [tianshanghong/awesome-anki#16]
The ultimate geography deck
https://github.com/axelboc/anki-ultimate-geography 
has a standard version of the deck that comes with four note templates: Flag - Country, Map - Country, Country - Capital and Capital - Country.

The deck's comprehensive tag structure allows for the creation of filtered decks covering a wide range of learning goals.

**Comment by tianshanghong** [comment]
Sorry for the late reply. Thank you for the Issue. I've added it to the README.md.
