### ISSUE TITLE
Add Addon: AnkiCollab

### ISSUE THREAD

**Issue by CravingCrates** [tianshanghong/awesome-anki#45]
AnkiCollab is an open-source, 100% free, mass collaboration tool to create and share Anki decks

https://github.com/CravingCrates/AnkiCollab-Plugin

**Comment by tianshanghong** [comment]
Thanks for the recommendation. Just added it https://github.com/tianshanghong/awesome-anki/commit/5c0ff24ca3c8cd1935d493636ec1fbb3eb575b24
