### ISSUE TITLE
Github topics

### ISSUE THREAD

**Issue by AurelienLourot** [tianshanghong/awesome-anki#5]
Hi @tianshanghong :) I think you should define Github topics so that people can easily find your list:

![topics](https://lh3.googleusercontent.com/KfOXDGRO83urAmJvn5RJVCScTI4yJXXIDiJaiKUv2Hwm6TwkdIeepS9C1M-myu3hDXWqY0A9ZBBi_q59dHZ2D3ZqR5EhfbCImtdvSFGYVQGNSe_mofTNPppMpBPptAUX40zJ7guLoi4m8eu8B6PzZB6LwQbB20ggMUfjoVzG-oIJ0SCCXnZkpO_Mf7Zvf4W8iNjaDpXwDXE5GQqS3IzWHe4Lcpwba7x9gyz8QA5EW-IQCJmWAZ1KGWkaOC4tCv-9-6SaZETTYLJ7lbYYt2NxUv0Fu8e1dqBoQgjDZDOsBqq56c1dOPatlqOej8mhFSAAZkMBTeep7QEqX_JHo3mWRYvQCV2y7lKysnx5eDimFRvqiJTHmfNPUCya7e3-jZXPEu3GI6B70CL-iqgc9i3PYeQYUeWBlWr-n7u_wRaHZ8nq_zrv3_JwTrvlSVHpyIZMqzpY8C3bheaAP_0u_TTlYdVk_yMjxa8x-8FQ1ZWJ4Z3c60OnDCwj1JgOHoXgXat4rvIjdLGGdsQMPbzfKAaPQaziNT5FzHeMMdsudUEI2-ruDYNSHDfhXZi4OoVIX4OWUNDafrnqPBTHdW0MGhJngm7spuRs8swv9Nr0L5pY6KQFrmO8KoBuReebyf0q1iSkXrmPTcJ3D4_67OnFnT9siMKaVeTSmWsq=w466-h137-no)

**Comment by tianshanghong** [comment]
Yeah, really nice advice. Thanks for that!
