### ISSUE TITLE
Add MedAnkiGen

### ISSUE THREAD

**Issue by alawi2306** [tianshanghong/awesome-anki#57]
Hi there,

I hope you're doing well! I’ve recently developed a tool called MedAnkiGen which helps users create custom Anki cards from medical texts and lectures. It’s designed to save time and make studying more efficient for medical students.

I really like your directory, and I thought it might be a good fit for your audience. If you’re interested, would you consider adding MedAnkiGen to your list of Anki tools? I’d really appreciate your consideration!

Here’s the link to the tool for your reference:  
[www.medankigen.com](url)  

Thank you so much for your time and for maintaining such an awesome list of resources for the community!

PS: Here is a screenshot of the tool.

![Screenshot 2024-12-15 145041](https://github.com/user-attachments/assets/a8a1ee83-35e1-46fd-92a8-70186a26a03f)

**Comment by tianshanghong** [comment]
Looks cool! Would you mind creating a PR @alawi2306

**Comment by alawi2306** [comment]
Absolutely! I have created a pr for you to look at, thank you.

**Comment by tianshanghong** [comment]
Thanks! Just merged the PR. #58
